name: create-tag-version

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install jq
        run: sudo apt-get update && sudo apt-get install -y jq

      - name: Make tag_version.sh executable
        run: chmod +x buildscripts/tag_version.sh

      - name: Bump version and push tag
        id: tag_version
        run: |
          new_version=$(./buildscripts/tag_version.sh)
          echo "new_version=$new_version" >> $GITHUB_ENV

      - name: Create a GitHub release
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ env.new_version }}
          name: Release ${{ env.new_version }}
          body: "Release version ${{ env.new_version }}"
